export const reportContent = {
  introduction: `The project generates synthetic celebrity face images to augment limited real datasets for training robust image classification models. This is particularly valuable in scenarios with scarce labeled data, such as medical imaging or rare event detection, where synthetic data can enhance model generalization and performance without compromising privacy or requiring extensive manual annotation.`,
  dataPreparation: {
    main: `
      **2.1 Dataset Loading:** The CelebA dataset, comprising 202,599 celebrity face images, was accessed using a custom PyTorch CustomCelebADataset class. This class integrated image data with attribute and partition information from provided CSV files (list_attr_celeba.csv and list_eval_partition.csv). The "Young" attribute, originally encoded as -1 (not young) and 1 (young), was remapped to 0 and 1, respectively, for binary classification tasks in later stages.

      **2.2 Image Preprocessing:** Images were resized to a uniform resolution of (3 x 64 x 64) to ensure compatibility with the Wasserstein GAN (WGAN) and classifier models. A PyTorch transform pipeline was applied, which included converting images to tensors and normalizing pixel values with a mean of 0.5 and a standard deviation of 0.5 across RGB channels. This normalization stabilized training by ensuring consistent input distributions.

      **2.3 Dataset Splitting and Subsampling:** The dataset was partitioned into training, validation, and test sets based on the partition indices provided in the CelebA dataset (0: training, 1: validation, 2: test). To manage computational resources, a subset of 30,000 images was randomly sampled while preserving the original proportional split (approximately 80% training, 10% validation, 10% test). This resulted in 24,102 training images, 2,941 validation images, and 2,957 test images. Random sampling was performed with a fixed seed (42) for reproducibility.

      **2.4 DataLoader Setup:** PyTorch DataLoader objects were created for each subset to enable efficient batch processing. A batch size of 128 was chosen to balance memory usage and training speed. The training DataLoader was set to shuffle data for better model generalization, while the validation and test DataLoaders used sequential sampling to ensure consistent evaluation.
    `,
    visualization: `To verify preprocessing, a grid of 16 training images was visualized using a custom imshow function. The images were denormalized (reversing the mean=0.5, std=0.5 transformation) for display. The visualization confirmed that images retained clear facial features, with correct resizing and color normalization, ensuring the data was suitable for WGAN training and classification tasks.`,
  },
  wganImplementation: {
    main: `
      **3.1 Model Architecture:** A Wasserstein GAN (WGAN) with gradient penalty was developed to generate synthetic CelebA images. The generator took a 100-dimensional latent vector as input and used five transposed convolutional layers with batch normalization and ReLU activations, followed by a Tanh activation to output 3x64x64 RGB images. The discriminator (critic) consisted of five convolutional layers with LeakyReLU activations, producing a single scalar to evaluate image realism.

      **3.2 Training Procedure:** The WGAN was trained for 30 epochs on the training dataset of 24,102 images using the Adam optimizer with a learning rate of 0.0001 and beta parameters (0.0, 0.9). The discriminator was updated five times per generator update to ensure stable critic training. A gradient penalty with a weight of 10 was applied to enforce the Lipschitz constraint, calculated using interpolated samples between real and fake images. The discriminator loss was based on the Wasserstein distance (difference in critic outputs for real and fake images) plus the gradient penalty, while the generator loss minimized the negative critic output for generated images.
    `,
    lossVisualization: `Losses for the generator and discriminator were tracked and plotted over training iterations.`,
    generatedImages: `A grid of 16 synthetic images was generated from random latent vectors and visualized. The images displayed recognizable facial features, such as eyes, noses, and hair, though minor artifacts like slight blurriness were observed. This visual inspection confirmed that the generator produced plausible face images resembling the CelebA dataset.`,
    evaluation: `The quality of synthetic images was assessed using Inception Score (IS) and Fréchet Inception Distance (FID). A pretrained Inception V3 model was used to compute these metrics on 2,500 generated images and 128 real images, resized to 299x299.`,
  },
  hyperparameterTuning: {
    main: `
      **4.1 Tuning Setup:** Hyperparameter optimization was performed using the Optuna library to enhance the quality of synthetic images generated by the WGAN. The objective was to minimize the Fréchet Inception Distance (FID) score, a key metric for assessing the similarity between real and synthetic image distributions. Four hyperparameters were tuned: learning rate (range: \\(10^{-5}\\) to \\(10^{-3}\\), log scale), batch size (choices: 32, 64, 128), latent dimension (choices: 64, 100, 128), and number of critic updates per generator update (range: 3 to 10). Five trials were conducted, each training a WGAN for 10 epochs.

      **4.2 Optimization Results:** The best trial yielded an FID of 748.77 with the following hyperparameters: learning rate = 0.000414, batch size = 64, latent dimension = 64, and number of critic updates = 9. Subsequent evaluation showed variability due to limited real image samples. Other trials produced higher FID scores (ranging from 801.29 to 1433.70), highlighting the sensitivity of WGAN performance to hyperparameter choices.

      **4.3 Retraining with Optimal Parameters:** Using the optimal hyperparameters, the WGAN was retrained for 30 epochs on the training dataset (24,102 images). The training process followed the same WGAN algorithm with a gradient penalty weight of 10, ensuring stable convergence similar to the initial setup.
    `,
     quality: `The retrained WGAN generated 2,500 synthetic images for evaluation. The Inception Score (IS) improved from the initial model, while the FID score increased, suggesting a larger distributional gap possibly due to inconsistencies in the limited real image sample or overfitting.`,
    visual: `A grid of 16 synthetic images generated post-tuning was visualized. Compared to the initial model, the tuned model produced images such that some have sharper facial features, such as eyes and defined hairlines while others are visually poor reflecting the improvement in IS and degradation in FID. This suggests a strong need for better hyperparameter tuning which in turn needs much better compute resource.`,
  },
  classifierReal: {
    main: `
      **5.1 Model Architecture:** A convolutional neural network (CNN) classifier was designed to perform binary classification of CelebA faces as "Young" or "Old" based on the "Young" attribute. The CNN comprised three convolutional layers with ReLU activations and max-pooling, followed by two fully connected layers with a ReLU activation, dropout (0.5) for regularization, and a sigmoid output to produce probabilities.

      **5.2 Training Procedure:** The classifier was trained for 30 epochs on the real training dataset (24,102 images) using the Adam optimizer with a learning rate of 0.001 and a batch size of 128. The binary cross-entropy loss (BCELoss) was used as the loss function. Training progress was monitored by computing the average training loss per epoch. Validation was performed on the validation dataset (2,941 images) to track loss and accuracy, ensuring proper model learning and preventing overfitting.
    `,
    performance: `Training and validation losses were tracked in each epoch, alongside validation accuracy.`,
    evaluation: `The trained model was evaluated on the test dataset (2,957 images).`,
  },
  annotatingSynthetic: {
    main: `
      **6.1 Synthetic Data Generation:** The trained Wasserstein GAN (WGAN) with optimized hyperparameters (latent dimension = 64) was used to generate 16,871 synthetic images, equivalent to 70% of the real training dataset size (24,102 images). The generator produced images in batches of 128, with each image being a (3 x 64 x 64) RGB face sample derived from random latent vectors.

      **6.2 Annotation Process:** The previously trained CNN classifier, loaded from cnn_classifier_real_data.pth, was used to annotate the synthetic images. The classifier, set to evaluation mode, predicted binary labels ("Young" or "Old") for each synthetic image by applying a threshold of 0.5 to its sigmoid output. Annotations were performed in batches concurrently with image generation to optimize computational efficiency, resulting in 16,871 labeled synthetic images.
    `,
  },
  classifierMixed: {
    main: `
      **7.1 Dataset Preparation:** A mixed dataset was created by combining 16,871 synthetic images (70% of the original training dataset size) with 16,871 randomly sampled real images from the training dataset, resulting in a total of 33,742 images. The synthetic images and their corresponding "Young" or "Old" labels, generated and annotated in Part 6, were loaded from saved tensors. The real images were selected using random permutation to ensure diversity. A PyTorch ConcatDataset was used to merge the synthetic and real datasets, and a DataLoader was created with a batch size of 128 and shuffling enabled to facilitate training.

      **7.2 Model Training:** A new CNN classifier, identical in architecture to the one used in Part 5 (three convolutional layers with ReLU and max-pooling, followed by two fully connected layers with dropout and sigmoid output), was trained on the combined dataset for 30 epochs. The Adam optimizer with a learning rate of 0.001 and binary cross-entropy loss were employed. Training loss was monitored and decreased consistently, stabilizing around 0.30, indicating effective learning on the mixed dataset.
    `,
    evaluation: `The trained classifier was evaluated on the real test dataset (2,957 images) to assess its performance and compare it against the classifier trained solely on real data.`,
    analysis: `The classifier trained on the mixed dataset achieved strong performance, with metrics only slightly lower than those of the real-data-only model. The slight decline in accuracy, recall, and F1-score suggests that synthetic images, while useful, introduced some noise or artifacts that mildly affected generalization. However, the marginal improvement in precision indicates better identification of true "Young" cases. These results highlight the potential of synthetic data to augment real data, maintaining competitive classification performance despite the challenges posed by synthetic image imperfections.`,
  },
};

// Chart Data (Sample - replace with actual data)
export const initialWganLossData = Array.from({ length: 30 }, (_, i) => ({
  epoch: i + 1,
  generatorLoss: Math.random() * 2 + 0.5, // Simulate decreasing loss
  discriminatorLoss: Math.random() * 1 + 0.2, // Simulate stable loss
}));

export const classifierRealLossData = Array.from({ length: 30 }, (_, i) => ({
  epoch: i + 1,
  trainingLoss: 0.8 / (i + 1) + 0.1 + Math.random() * 0.1, // Simulate decreasing loss
  validationLoss: 0.7 / (i + 1) + 0.15 + Math.random() * 0.1, // Simulate decreasing loss
}));

export const classifierRealAccuracyData = Array.from({ length: 30 }, (_, i) => ({
  epoch: i + 1,
  validationAccuracy: 0.6 + (0.25 * i) / 29 + Math.random() * 0.05, // Simulate increasing accuracy
}));

export const metricComparisonData = [
  { metric: 'Accuracy', realOnly: 0.8380, mixed: 0.8157 },
  { metric: 'Precision', realOnly: 0.8504, mixed: 0.8564 },
  { metric: 'Recall', realOnly: 0.9524, mixed: 0.9075 },
  { metric: 'F1-Score', realOnly: 0.8985, mixed: 0.8812 },
];
